darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolov4_bs.cfg
      weight_file:
        name: yolov4_bs.weights
      threshold:
        value: 0.7
      detection_classes:
        names:
          - "1300"
          - "1301"
          - "1302"
          - "1303"
          - "1305"
          - "1306"
          - "1400"
          - "1401"
          - "1402"
          - "1403"
          - "1404"
          - "1405"
          - "1406"
          - "1407"
          - "A1"
          - "A2"
          - "A3"
          - "B1"
          - "B2"
          - "B3"

