darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolov4-obj.cfg
      weight_file:
        name: yolov4-obj_cone_tracking.weights
      threshold:
        value: 0.7
      detection_classes:
        names:
        - y_cone
        - b_cone
        - stop
      
