# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)

    save:
      mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver
                                # Manager, Antenna, and Logging Configuration
      device: 4                 # Save to EEPROM

    device: /dev/ttyACM0
    frame_id: gps
    dynamic_model: automotive   # Velocity restricted to 0 m/s. Zero dynamics
                                # assumed.
    fix_mode: auto
    dr_limit: 0
    enable_ppp: false           # Not supported by C94-M8P

    rate: 10.0                   # Measurement rate in Hz
    nav_rate: 1                 # in number of measurement cycles

    uart1:
      baudrate: 115200           # C94-M8P specific
      in: 0                     # No UART in for base
      out: 32                   # RTCM 3

    # TMODE3 Config
    tmode3:                    # Survey-In Modes
    sv_in:
      reset: true               # True: disables and re-enables survey-in (resets)
                                # False: Disables survey-in only if TMODE3 is
                                # disabled
      min_dur: 300              # Survey-In Minimum Duration [s]
      acc_lim: 3.0              # Survey-In Accuracy Limit [m]

    # # RTCM out config
    # rtcm:
    #   ids: [5, 87, 77, 230]     # RTCM Messages to configure for Base station
    #                                    # Enabled: GPS MSM7, GLONASS MSM7,
    #                                    # GLONASS CP bias, Stationary RTK ref
    #                                    # 0xF5 0x05 Stationary RTK reference station
    #                                    # ARP
    #                                    # 0xF5 0x4A GPS MSM4
    #                                    # 0xF5 0x4D GPS MSM7
    #                                    # 0xF5 0x54 GLONASS MSM4
    #                                    # 0xF5 0x57 GLONASS MSM7
    #                                    # 0xF5 0x7C BeiDou MSM4
    #                                    # 0xF5 0x7F BeiDou MSM7
    #                                    # 0xF5 0xE6 GLONASS code-phase biases
    #                                    # 0xF5 0xFE Reference station PVT
    #                                    #(u-blox proprietary RTCM Message)
    #   rates: [1, 1, 1, 10]      # in number of navigation solutions, must match
                                # nav_rate, except for 0xE6
    dgnss_mode: 3               # Fixed mode

    dat:
      set: false

    # GNSS Config
    gnss:
      gps:      true   # GPS는 항상 true
      sbas:     true  # WAAS·EGNOS 등 위성보정
      galileo:  true
      beidou:   true
      imes:     false
      qzss:     true
      glonass:  true
      irnss:    false  # (M8P는 미지원이지만 명시적으로 꺼 줌)
            # Supported by C94-M8P

    inf:
      all: true                   # Whether to display all INF messages in console

    # Enable u-blox message publishers
    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false
