# Configuration Settings for C099-F9P device  (Autonomous-Vehicle Rover)
ublox_gps_node:
  ros__parameters:
    debug: 0

    save:
      mask: 3103
      device: 4

    device: /dev/ttyACM0
    frame_id: gps

    # ─ Navigation rate ─
    rate: 8.0          # 8 Hz → 필요하면 10 Hz로 상향
    nav_rate: 1

    # ─ Navigation engine ─
    # dynamic_model: automotive   # 차량용 모델
    dynamic_model: portable
    fix_mode: auto
    enable_ppp: false
    dr_limit: 0

    # ─ TMODE3 ─
    tmode3: 0          # Disabled (rover)
    sv_in:
      reset: false
      min_dur: 300
      acc_lim: 3.0

    # ─ UART1 (사용 안 하면 무시) ─
    uart1:
      baudrate: 19200
      in: 32
      out: 0

    # ─ GNSS ─
    gnss:
      gps:      true
      sbas:     true
      galileo:  true
      beidou:   true
      qzss:     true
      glonass:  true
      imes:     false
      irnss:    false

    dgnss_mode: 3      # RTK Fixed 사용

    inf:
      all: false

    # ─ ROS topic publish ─
    publish:
      all: true
      nav:
        pvt: false      